default:
  email_delivery:
  delivery_method: :smtp
  smtp_settings:
    address: smtp.sendgrid.net
    port: 587
    enable_starttls_auto: true
    domain: carragroup.org
    authentication: :plain
    user_name: <%= ENV['SENDGRID_USERNAME'] %>
    password: <%= ENV['SENDGRID_PASSWORD'] %>
