production:
  email_delivery:
  delivery_method: :smtp
  smtp_settings:
    address: connect.carragroup.org
    port: 465
    enable_starttls_auto: true
    domain: carragroup.org
    authentication: :login
    user_name: <%= ENV['EMAIL_ACCOUNT'] %>
    password: <%= ENV['SMTP_PASSWORD'] %>
